name: Ejercicio 5

env:
  APP_NAME: "Quiz App"
  VERSION: "1.0.0"

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.create_timestamp.outputs.timestamp }}

    steps:
      - name: Mostrar informaciÃ³n de la app
        run: echo "Aplicacion: $APP_NAME v$VERSION"

      - name: Crear timestamp
        id: create_timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

  test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Crear archivo con datos
        run: |
          echo "Nombre: $APP_NAME" > app-info.txt
          echo "Version: $VERSION" >> app-info.txt
          echo "Timestamp: ${{ needs.setup.outputs.timestamp }}" >> app-info.txt

      - uses: actions/upload-artifact@v4
        with:
          name: app-info
          path: app-info.txt
